/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    enquiries: Enquiry;
    pages: Page;
    faqs: Faq;
    galleries: Gallery;
    venues: Venue;
    events: Event;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    enquiries: EnquiriesSelect<false> | EnquiriesSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    galleries: GalleriesSelect<false> | GalleriesSelect<true>;
    venues: VenuesSelect<false> | VenuesSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'home-page': HomePage;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name: string;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  caption?: string | null;
  credit?: string | null;
  orientation: 'vertical' | 'horizontal' | 'square';
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    wide?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    social?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries".
 */
export interface Enquiry {
  id: string;
  status: 'new' | 'contacted' | 'proposal' | 'confirmed' | 'closed';
  assignedTo?: (string | null) | User;
  lastContactedAt?: string | null;
  internalNotes?: string | null;
  contact: {
    firstName?: string | null;
    lastName?: string | null;
    contactName: string;
    email: string;
    phone: string;
  };
  contactName: string;
  schoolDetails: {
    school: string;
    county: string;
    joiningSchools?: string | null;
    yearSize?: number | null;
  };
  school: string;
  county: string;
  eventDetails: {
    eventType?: ('debs' | 'ty_ball') | null;
    preferredDate?: string | null;
    preferredLocation?: string | null;
    attendanceBand?: ('50_80' | '80_120' | '120_150' | 'more_than_150') | null;
    estimatedAttendance: number;
    message?: string | null;
  };
  preferredDate?: string | null;
  source?: {
    referralSource?: string | null;
    referralOther?: string | null;
    landingPage?: string | null;
    referrer?: string | null;
    utmSource?: string | null;
    utmMedium?: string | null;
    utmCampaign?: string | null;
    utmContent?: string | null;
    utmTerm?: string | null;
    gclid?: string | null;
    fbclid?: string | null;
  };
  privacy: {
    noticeAcknowledgedAt: string;
    marketingConsent: boolean;
  };
  notification: {
    status: 'pending' | 'sent' | 'failed';
    error?: string | null;
  };
  requestHash: string;
  legacyCreatedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  slug: 'how-it-works' | 'cost-guide' | 'parents-schools' | 'for-committees' | 'enquire';
  hero: {
    eyebrow: string;
    title: string;
    intro: string;
    media?: (string | null) | Media;
  };
  /**
   * Section keys are used by the fixed site design. Edit copy and order; do not rename a key unless the frontend is updated.
   */
  sections: {
    key: string;
    eyebrow?: string | null;
    title: string;
    text?: string | null;
    items?:
      | {
          title: string;
          text: string;
          id?: string | null;
        }[]
      | null;
    id?: string | null;
  }[];
  callToAction: {
    eyebrow: string;
    title: string;
    text?: string | null;
    buttonLabel: string;
    buttonLink: string;
  };
  seo: {
    title: string;
    description: string;
    image?: (string | null) | Media;
    canonicalPath: string;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: string;
  _order?: string | null;
  question: string;
  answer: string;
  page: 'home' | 'parents-schools' | 'for-committees' | 'cost-guide';
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "galleries".
 */
export interface Gallery {
  id: string;
  title: string;
  slug: string;
  description?: string | null;
  items: {
    media: string | Media;
    caption?: string | null;
    id?: string | null;
  }[];
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "venues".
 */
export interface Venue {
  id: string;
  title: string;
  slug: string;
  county: string;
  area: string;
  summary: string;
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  heroMedia: string | Media;
  gallery?: (string | null) | Gallery;
  features?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  seo: {
    title: string;
    description: string;
    image?: (string | null) | Media;
    canonicalPath: string;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: string;
  title: string;
  slug: string;
  eventDate: string;
  county: string;
  venue?: (string | null) | Venue;
  summary: string;
  story: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  heroMedia: string | Media;
  gallery: string | Gallery;
  featured?: boolean | null;
  /**
   * Confirm that all public media is approved for website use.
   */
  photoConsentConfirmed: boolean;
  seo: {
    title: string;
    description: string;
    image?: (string | null) | Media;
    canonicalPath: string;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'enquiries';
        value: string | Enquiry;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'faqs';
        value: string | Faq;
      } | null)
    | ({
        relationTo: 'galleries';
        value: string | Gallery;
      } | null)
    | ({
        relationTo: 'venues';
        value: string | Venue;
      } | null)
    | ({
        relationTo: 'events';
        value: string | Event;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  credit?: T;
  orientation?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        wide?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        social?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries_select".
 */
export interface EnquiriesSelect<T extends boolean = true> {
  status?: T;
  assignedTo?: T;
  lastContactedAt?: T;
  internalNotes?: T;
  contact?:
    | T
    | {
        firstName?: T;
        lastName?: T;
        contactName?: T;
        email?: T;
        phone?: T;
      };
  contactName?: T;
  schoolDetails?:
    | T
    | {
        school?: T;
        county?: T;
        joiningSchools?: T;
        yearSize?: T;
      };
  school?: T;
  county?: T;
  eventDetails?:
    | T
    | {
        eventType?: T;
        preferredDate?: T;
        preferredLocation?: T;
        attendanceBand?: T;
        estimatedAttendance?: T;
        message?: T;
      };
  preferredDate?: T;
  source?:
    | T
    | {
        referralSource?: T;
        referralOther?: T;
        landingPage?: T;
        referrer?: T;
        utmSource?: T;
        utmMedium?: T;
        utmCampaign?: T;
        utmContent?: T;
        utmTerm?: T;
        gclid?: T;
        fbclid?: T;
      };
  privacy?:
    | T
    | {
        noticeAcknowledgedAt?: T;
        marketingConsent?: T;
      };
  notification?:
    | T
    | {
        status?: T;
        error?: T;
      };
  requestHash?: T;
  legacyCreatedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  hero?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        intro?: T;
        media?: T;
      };
  sections?:
    | T
    | {
        key?: T;
        eyebrow?: T;
        title?: T;
        text?: T;
        items?:
          | T
          | {
              title?: T;
              text?: T;
              id?: T;
            };
        id?: T;
      };
  callToAction?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        text?: T;
        buttonLabel?: T;
        buttonLink?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        canonicalPath?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  _order?: T;
  question?: T;
  answer?: T;
  page?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "galleries_select".
 */
export interface GalleriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  items?:
    | T
    | {
        media?: T;
        caption?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "venues_select".
 */
export interface VenuesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  county?: T;
  area?: T;
  summary?: T;
  description?: T;
  heroMedia?: T;
  gallery?: T;
  features?:
    | T
    | {
        text?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        canonicalPath?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  eventDate?: T;
  county?: T;
  venue?: T;
  summary?: T;
  story?: T;
  heroMedia?: T;
  gallery?: T;
  featured?: T;
  photoConsentConfirmed?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        canonicalPath?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: string;
  siteName: string;
  siteDescription: string;
  contactEmail: string;
  whatsappNumber: string;
  whatsappLabel: string;
  socialLinks: {
    instagram: string;
    facebook: string;
    tiktok: string;
    debsGuru: string;
  };
  footerStatement: string;
  defaultSocialImage?: (string | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: string;
  hero: {
    eyebrow: string;
    title: string;
    intro: string;
    primaryButtonLabel: string;
    primaryButtonLink: string;
    secondaryButtonLabel: string;
    secondaryButtonLink: string;
  };
  highlights: {
    icon: 'venue' | 'contact' | 'shield';
    title: string;
    text: string;
    id?: string | null;
  }[];
  experience: {
    eyebrow: string;
    title: string;
    categories: {
      name: string;
      video: string | Media;
      poster: string | Media;
      id?: string | null;
    }[];
  };
  proof: {
    eyebrow: string;
    title: string;
    text: string;
    gallery?: (string | null) | Gallery;
  };
  steps: {
    title: string;
    text: string;
    id?: string | null;
  }[];
  parentGuidance: {
    eyebrow: string;
    title: string;
    points: {
      text: string;
      id?: string | null;
    }[];
  };
  finalCallToAction: {
    eyebrow: string;
    title: string;
    text: string;
    buttonLabel: string;
    buttonLink: string;
  };
  seo: {
    title: string;
    description: string;
    image?: (string | null) | Media;
    canonicalPath: string;
    noIndex?: boolean | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  siteDescription?: T;
  contactEmail?: T;
  whatsappNumber?: T;
  whatsappLabel?: T;
  socialLinks?:
    | T
    | {
        instagram?: T;
        facebook?: T;
        tiktok?: T;
        debsGuru?: T;
      };
  footerStatement?: T;
  defaultSocialImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        intro?: T;
        primaryButtonLabel?: T;
        primaryButtonLink?: T;
        secondaryButtonLabel?: T;
        secondaryButtonLink?: T;
      };
  highlights?:
    | T
    | {
        icon?: T;
        title?: T;
        text?: T;
        id?: T;
      };
  experience?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        categories?:
          | T
          | {
              name?: T;
              video?: T;
              poster?: T;
              id?: T;
            };
      };
  proof?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        text?: T;
        gallery?: T;
      };
  steps?:
    | T
    | {
        title?: T;
        text?: T;
        id?: T;
      };
  parentGuidance?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        points?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  finalCallToAction?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        text?: T;
        buttonLabel?: T;
        buttonLink?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        canonicalPath?: T;
        noIndex?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}